### ISSUE TITLE
Caused by: java.lang.NoSuchMethodException: net.razorvine.pickle.objects.ClassDict.__setstate__([Ljava.lang.Object;)

### ISSUE THREAD

**Issue by john-ghaly** [jpmml/jpmml-sklearn#106]
Standard output is empty
Standard error:
Jun 26, 2019 2:26:46 PM org.jpmml.sklearn.Main run
INFO: Parsing PKL..
Jun 26, 2019 2:26:56 PM org.jpmml.sklearn.Main run
SEVERE: Failed to parse PKL
net.razorvine.pickle.PickleException: failed to __setstate__()
	at net.razorvine.pickle.Unpickler.load_build(Unpickler.java:368)
	at net.razorvine.pickle.Unpickler.dispatch(Unpickler.java:221)
	at org.jpmml.sklearn.PickleUtil$1.dispatch(PickleUtil.java:77)
	at net.razorvine.pickle.Unpickler.load(Unpickler.java:122)
	at org.jpmml.sklearn.PickleUtil.unpickle(PickleUtil.java:98)
	at org.jpmml.sklearn.Main.run(Main.java:104)
	at org.jpmml.sklearn.Main.main(Main.java:94)
Caused by: java.lang.NoSuchMethodException: net.razorvine.pickle.objects.ClassDict.__setstate__([Ljava.lang.Object;)
	at java.lang.Class.getMethod(Class.java:1786)
	at net.razorvine.pickle.Unpickler.load_build(Unpickler.java:365)
	... 6 more

Exception in thread "main" net.razorvine.pickle.PickleException: failed to __setstate__()
	at net.razorvine.pickle.Unpickler.load_build(Unpickler.java:368)
	at net.razorvine.pickle.Unpickler.dispatch(Unpickler.java:221)
	at org.jpmml.sklearn.PickleUtil$1.dispatch(PickleUtil.java:77)
	at net.razorvine.pickle.Unpickler.load(Unpickler.java:122)
	at org.jpmml.sklearn.PickleUtil.unpickle(PickleUtil.java:98)
	at org.jpmml.sklearn.Main.run(Main.java:104)
	at org.jpmml.sklearn.Main.main(Main.java:94)
Caused by: java.lang.NoSuchMethodException: net.razorvine.pickle.objects.ClassDict.__setstate__([Ljava.lang.Object;)
	at java.lang.Class.getMethod(Class.java:1786)
	at net.razorvine.pickle.Unpickler.load_build(Unpickler.java:365)
	... 6 more

I tried:
- converting to numpy array and back to pandas dataframe
- Resetting the index and deleting it
- Selecting 10 rows and 2 columns with no missing values and visually inspect the data
- Pass only numeric data types 'float64', 'int64'
- Pass Object (Using LabelBinarizer()) and numeric types
- ran X.dtypes.value_counts() to check for any weird data type (only float64, int64)

Pandas version: 0.23.4
Numpy version: 1.15.4
Xgboost version: 0.81
sklearn version: 0.20.3
sklearn2pmml version: 0.47.0

**Comment by john-ghaly** [comment]
Villu's answer:
Hi John,

Support requests should be directed to GitHub issues:
https://github.com/jpmml/jpmml-sklearn/issues

> Caused by: java.lang.NoSuchMethodException: net.razorvine.pickle.objects.ClassDict.__setstate__([Ljava.lang.Object;)
> at java.lang.Class.getMethod(Class.java:1786)
> at net.razorvine.pickle.Unpickler.load_build(Unpickler.java:365)
> ... 6 more
>

Your pickle file contains a non-standard CPython class (ie. defines
custom __setstate__() method), which can't be unpickled using the
standard procedure.

You need to figure out which CPython object/class it is, and then
either get rid of it, or transform it to some standard (C)Python
object.

> - converting to numpy array and back to pandas dataframe
> - Resetting the index and deleting it

I have a hunch that this CPython object is related to Pandas indexing,
and is attached to the PMMLPipeline object via PMMLPipeline.fit(X, y)
or PMMLPipeline.verify(X) methods.

**Comment by john-ghaly** [comment]
Hi Villu, Thank you for your reply by email (posted above). Can you please elaborate on how to get rid of CPython object related to Pandas indexing? Before updating to 0.47 I was using 0.42 and the error message mentioned pandas._new_index but I still couldn't figure it out.

I tried converting to numpy and then creating a new dataframe with index = None
Also tried:
X.reset_index()
del X['index']
Still getting the same error

**Comment by vruusmann** [comment]
> Can you please elaborate on how to get rid of CPython object related to Pandas indexing?

This is an expert-level stuff, and I'm not an expert.

Instead, I would try to seek confirmation that this issue is really caused by Pandas indexing. After you've done your real "data science work", save the `pandas.DataFrame` object to a CSV file, and then re-load a default/clean `pandas.DataFrame` object using the `pandas.read_csv(path)` method.

If you fit the pipeline using this default/clean `pandas.DataFrame` object, then the conversion is expected to succeed.

**Comment by john-ghaly** [comment]
Hi Villu,

I tried exporting to csv and it didn't work cause the problem was in the xgboost classifier. I mistakenly copy pasted the eval_set = eval_set from the test classifier to the final model.
Once I deleted the eval_set from the classifier everything worked.

Thank you for your help, the csv idea helped realize that it is not a data problem.
