### ISSUE TITLE
fail to convert gbdt model

### ISSUE THREAD

**Issue by NJChrishong** [jpmml/jpmml-sklearn#107]
```
Standard output is empty
Standard error:
 27, 2019 5:25:48  org.jpmml.sklearn.Main run
Ϣ: Parsing PKL..
 27, 2019 5:25:48  org.jpmml.sklearn.Main run
Ϣ: Parsed PKL in 46 ms.
 27, 2019 5:25:48  org.jpmml.sklearn.Main run
Ϣ: Converting..
 27, 2019 5:25:48  sklearn2pmml.pipeline.PMMLPipeline initTargetFields
: Attribute 'sklearn2pmml.pipeline.PMMLPipeline.target_fields' is not set. Assuming y as the name of the target field
 27, 2019 5:25:48  sklearn2pmml.pipeline.PMMLPipeline initActiveFields
: Attribute 'sklearn2pmml.pipeline.PMMLPipeline.active_fields' is not set. Assuming [x1, x2, x3, x4] as the names of active fields
 27, 2019 5:25:48  org.jpmml.sklearn.Main run
: Failed to convert
java.lang.IndexOutOfBoundsException: Index: 1, Size: 1
	at java.util.ArrayList.rangeCheck(ArrayList.java:653)
	at java.util.ArrayList.get(ArrayList.java:429)
	at com.google.common.collect.Lists$TransformingRandomAccessList.get(Lists.java:599)
	at com.google.common.collect.Iterables.get(Iterables.java:728)
	at sklearn.ensemble.gradient_boosting.LogOddsEstimator.getPriorProbability(LogOddsEstimator.java:35)
	at sklearn.ensemble.gradient_boosting.BinomialDeviance.computeInitRawPrediction(BinomialDeviance.java:35)
	at sklearn.ensemble.gradient_boosting.GradientBoostingClassifier.encodeModel(GradientBoostingClassifier.java:83)
	at sklearn.ensemble.gradient_boosting.GradientBoostingClassifier.encodeModel(GradientBoostingClassifier.java:43)
	at sklearn2pmml.pipeline.PMMLPipeline.encodePMML(PMMLPipeline.java:217)
	at org.jpmml.sklearn.Main.run(Main.java:145)
	at org.jpmml.sklearn.Main.main(Main.java:94)

Exception in thread "main" java.lang.IndexOutOfBoundsException: Index: 1, Size: 1
	at java.util.ArrayList.rangeCheck(ArrayList.java:653)
	at java.util.ArrayList.get(ArrayList.java:429)
	at com.google.common.collect.Lists$TransformingRandomAccessList.get(Lists.java:599)
	at com.google.common.collect.Iterables.get(Iterables.java:728)
	at sklearn.ensemble.gradient_boosting.LogOddsEstimator.getPriorProbability(LogOddsEstimator.java:35)
	at sklearn.ensemble.gradient_boosting.BinomialDeviance.computeInitRawPrediction(BinomialDeviance.java:35)
	at sklearn.ensemble.gradient_boosting.GradientBoostingClassifier.encodeModel(GradientBoostingClassifier.java:83)
	at sklearn.ensemble.gradient_boosting.GradientBoostingClassifier.encodeModel(GradientBoostingClassifier.java:43)
	at sklearn2pmml.pipeline.PMMLPipeline.encodePMML(PMMLPipeline.java:217)
	at org.jpmml.sklearn.Main.run(Main.java:145)
	at org.jpmml.sklearn.Main.main(Main.java:94)
```

---------------------------------------------------------------------------
```
RuntimeError                              Traceback (most recent call last)
<ipython-input-48-3596247da6ac> in <module>
     25 pipeline = PMMLPipeline([("classifier", GradientBoostingClassifier())]);
     26 pipeline.fit(x_2,y_2)
---> 27 sklearn2pmml(pipeline, "demo1.pmml", with_repr = True)

D:\Software\Anaconda3\lib\site-packages\sklearn2pmml\__init__.py in sklearn2pmml(pipeline, pmml, user_classpath, with_repr, debug, java_encoding)
    250                                 print("Standard error is empty")
    251                 if retcode:
--> 252                         raise RuntimeError("The JPMML-SkLearn conversion application has failed. The Java executable should have printed more information about the failure into its standard output and/or standard error streams")
    253         finally:
    254                 if debug:

RuntimeError: The JPMML-SkLearn conversion application has failed. The Java executable should have printed more information about the failure into its standard output and/or standard error streams
```

my steps:
``` python
x_2=[[1,2,3,1]
   ,[2,4,1,5]
   ,[7,8,3,6]
   ,[4,8,4,7]
   ,[2,5,6,9]]

y_2=[0,1,0,1,1]

pipeline = PMMLPipeline([("classifier", GradientBoostingClassifier())]);
pipeline.fit(x_2,y_2)
sklearn2pmml(pipeline, "demo1.pmml", with_repr = True)
```

if i correct y_2=[0,1,0,2,1] ，multi classification,  process is no problem.
if i correct y_2=[0,1,0,1,1] ,   binary classification, process is on error.

**Comment by vruusmann** [comment]
What is your SkLearn2PMML and Scikit-Learn versions?

I'm running your binomial classification example using SkLearn2PMML 0.47.0 plus Scikit-Learn 0.21.1, and everything works OK.

**Comment by NJChrishong** [comment]
thanks , i will try your versions! Now sklearn2pmml 0.47.1 and sklearn 0.20.3 ，process is on error!

**Comment by NJChrishong** [comment]
Hello，i tried your versions ,it worked OK. But i used sklearn2pmml 0.47.1 and sklearn 0.20.3, it worked wrongly!
