### ISSUE TITLE
got a transformer object

### ISSUE THREAD

**Issue by adminhuyh** [jpmml/jpmml-sklearn#108]
java.lang.IllegalArgumentException: Expected an estimator object as the last step, got a transformer object (Python class sklearn.preprocessing.data.StandardScaler)
	at sklearn2pmml.pipeline.PMMLPipeline.getEstimator(PMMLPipeline.java:505)
	at sklearn2pmml.pipeline.PMMLPipeline.encodePMML(PMMLPipeline.java:100)
	at org.jpmml.sklearn.Main2.run(Main2.java:140)
	at org.jpmml.sklearn.Main2.main(Main2.java:74)

使用pipeline封装process中的方法，其中steps只有一步：labelencode or onehotencoder。未能转换成功，是否需要修改源码以支持单步转换。

**Comment by vruusmann** [comment]
This exception message is self-explanatory - the last step of a (PMML)Pipeline must be an estimator (some sort of classifier or regressor), not a transformer.

The conversion of transformer-only pipelines is discussed here: https://github.com/jpmml/jpmml-sklearn/issues/86
