### ISSUE TITLE
Getting Error while predicting xgboost pmml with more than 1 ntree_limit

### ISSUE THREAD

**Issue by jpyadava** [jpmml/jpmml-sklearn#120]
I am trying your example provided in Audit.py for more than 1 ntree_limit(for 1 tree it can predicts without an error).  Below is the code I am using(just using 1 continuous variable for simplicity, I am new working with PMMLs first time)

```python
from sklearn.preprocessing import LabelBinarizer
from sklearn_pandas import DataFrameMapper
from sklearn2pmml.decoration import CategoricalDomain, ContinuousDomain
from sklearn2pmml import PMMLPipeline, sklearn2pmml
from xgboost.sklearn import XGBClassifier
from pypmml import Model

mapper = DataFrameMapper(
	[([column], [ContinuousDomain()]) for column in ["Age"]]
)

classifier = XGBClassifier(objective = "binary:logistic", n_estimators = 100)
pipeline = PMMLPipeline([
	("mapper", mapper),
	("classifier", classifier)
])
model = pipeline.fit(df[["Age"]], df["Adjusted"])
pred_probs = model.predict_proba(df[["Age"]])[:,1]
classifier.ntree_limit = 1 # THIS!
sklearn2pmml(pipeline, "XGBoostAudit1.pmml")
#PMML Evaluation
model = Model.fromFile('XGBoostAudit1.pmml')
model.predict({"Age" : '45'})
```

Get below error when I run last statement to predict:
```
model.predict({"Age" : '45'})
Traceback (most recent call last):

  File "<ipython-input-184-4f5253799976>", line 1, in <module>
    model.predict({"Age" : '45'})

  File "C:\ProgramData\Anaconda3\lib\site-packages\pypmml\model.py", line 129, in predict
    return self.call('predict', data)

  File "C:\ProgramData\Anaconda3\lib\site-packages\pypmml\base.py", line 122, in call
    return call_java_func(getattr(self._java_model, name), *a)

  File "C:\ProgramData\Anaconda3\lib\site-packages\pypmml\base.py", line 41, in call_java_func
    return _java2py(func(*args))

  File "C:\ProgramData\Anaconda3\lib\site-packages\py4j\java_gateway.py", line 1257, in __call__
    answer, self.gateway_client, self.target_id, self.name)

  File "C:\ProgramData\Anaconda3\lib\site-packages\py4j\protocol.py", line 328, in get_return_value
    format(target_id, ".", name), value)

Py4JJavaError: An error occurred while calling o237.predict.
: java.lang.ArrayIndexOutOfBoundsException: 2
	at org.pmml4s.model.Model$$anonfun$prepare$1.apply$mcVI$sp(Model.scala:303)
	at scala.collection.immutable.Range.foreach$mVc$sp(Range.scala:160)
	at org.pmml4s.model.Model.prepare(Model.scala:287)
	at org.pmml4s.model.RegressionModel.predict(RegressionModel.scala:54)
	at org.pmml4s.model.Segment.predict(MiningModel.scala:384)
	at org.pmml4s.model.MiningModel$$anonfun$predict$1.apply(MiningModel.scala:111)
	at org.pmml4s.model.MiningModel$$anonfun$predict$1.apply(MiningModel.scala:109)
	at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
	at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:186)
	at org.pmml4s.model.MiningModel.predict(MiningModel.scala:109)
	at org.pmml4s.model.Model.predict(Model.scala:187)
	at sun.reflect.GeneratedMethodAccessor5.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:238)
	at java.lang.Thread.run(Unknown Source)
```
Thanks

**Comment by vruusmann** [comment]
You are working with two separate Python packages. First, you are converting the XGBoost model to PMML using the [SkLearn2PMML](https://github.com/jpmml/sklearn2pmml) package. Second, you are scoring this PMML using the PyPMML package.

The SkLearn2PMML part is doing just fine. The exception happens in the PyPMML part. I'm not affiliated with PyPMML in any way, so I have no way of knowing what's the problem there.

If you're looking to evaluate PMML in Python, then I'd recommend you to check out the [JPMML-Evaluator-Python](https://github.com/jpmml/jpmml-evaluator-python) package instead.
