### ISSUE TITLE
Support for uFunc Radians in ExpressionTransformer

### ISSUE THREAD

**Issue by akhnatal** [jpmml/jpmml-sklearn#134]
Hi Villu,

I'm trying to pass some complex formula to the ExpressionTransformer, only numpy uFunc, and I saw that the numpy.radians func is not supported  in :

[https://github.com/jpmml/jpmml-sklearn/blob/ea7cb8e7151fcd8018f331c9ff714d2af66a8995/src/main/java/numpy/core/UFuncUtil.java](url)

```
DISTANCE_HEADERS = [
    'driver-orders.deliveries.startLocationLatitude',
    'driver-orders.deliveries.startLocationLongitude',
    'drivers.latitude',
    'drivers.longitude'
]

formula = "numpy.log(numpy.clip(6371*(2*numpy.arcsin(numpy.sqrt(numpy.sin((numpy.radians(X[3])-numpy.radians(X[1]))/2.0)**2+numpy.cos(numpy.radians(X[1]))*numpy.cos(numpy.radians(X[3]))*numpy.sin((numpy.radians(X[2])-numpy.radians(X[0]))/2.0)**2))),0.1,100))"

def get_featurizer():
    
    return DataFrameMapper([
        (DISTANCE_HEADERS, [ContinuousDomain(), Alias(ExpressionTransformer(formula, dtype = np.float64), "driver_orig_distance")])
    ])

def get_pipeline():

    return PMMLPipeline([
        ('featurize', get_featurizer()),
        ('normalize', StandardScaler()),
        ('predict', LogisticRegression(solver='lbfgs'))
    ])
```

```
p = pmml_pipeline.get_pipeline()
p.fit(train_data, train_labels)
sklearn2pmml(p, "distance-baseline.pmml", with_repr = True)
```

```
SEVERE: Failed to convert
java.lang.IllegalArgumentException: radians
	at numpy.core.UFuncUtil.encodeNumpyUFunc(UFuncUtil.java:108)
```

Could you implement the radians uFunc ?

**Comment by vruusmann** [comment]
> Could you implement the radians uFunc ?

The "vocabulary" of supported Numpy universal functions is determined/limited by the "vocabulary" of PMML built-in functions: http://dmg.org/pmml/v4-4/BuiltinFunctions.html

Can you express the `radians` UFunc in terms of those PMML built-in functions? If yes, then please give me a hint, and it will be implemented. If not, then it's possible to consider extending the JPMML ecosystem (both converter and evaluator sides) with a vendor extension function.

**Comment by akhnatal** [comment]
I see, thanks for the explanation.

**Comment by vruusmann** [comment]
Reopening, because this is a kind of interesting topic.

The conversion between radians and degrees is very basic thing: https://en.wikipedia.org/wiki/Radian

There's probably no PMML built-in function for this, because it is assumed that people are able to divide and multiply by Math.PI themselves.

In the current case, SkLearn2PMML could generate a `DefineFunction` element `degtorad`, and invoke it everytime when there's the `radian` Numpy UFunc being used in the `ExpressionTransformer`.

**Comment by akhnatal** [comment]
The numpy.clip func is also not supported and yes I can easily replace it with: 
`np.maximum(a_min, np.minimum(a, a_max)) `

and ExpressionTransformer can't handle complex formula like :

`formula = "numpy.log(numpy.maximum(0.1, numpy.minimum(6371*(2*numpy.arcsin(numpy.sqrt(numpy.square(numpy.sin((0.0174533*X[3]-0.0174533*X[1])/2.0))+numpy.cos(0.0174533*X[1])*numpy.cos(0.0174533*X[3])*numpy.square(numpy.sin((0.0174533*X[2]-0.0174533*X[0])/2.0))))), 100)))"`

```
sklearn2pmml(p, "distance-baseline.pmml", with_repr = True)

Standard output is empty
Standard error:
May 21, 2020 10:26:58 AM org.jpmml.sklearn.Main run
INFO: Parsing PKL..
May 21, 2020 10:26:58 AM org.jpmml.sklearn.Main run
INFO: Parsed PKL in 27 ms.
May 21, 2020 10:26:58 AM org.jpmml.sklearn.Main run
INFO: Converting..
May 21, 2020 10:27:01 AM org.jpmml.sklearn.Main run
SEVERE: Failed to convert
java.lang.IllegalArgumentException
	at org.jpmml.sklearn.ExpressionTranslator.translateFunction(ExpressionTranslator.java:180)
	at org.jpmml.sklearn.ExpressionTranslator.FunctionInvocationExpression(ExpressionTranslator.java:642)
	at org.jpmml.sklearn.ExpressionTranslator.PrimaryExpression(ExpressionTranslator.java:537)
	at org.jpmml.sklearn.ExpressionTranslator.UnaryExpression(ExpressionTranslator.java:503)
	at org.jpmml.sklearn.ExpressionTranslator.MultiplicativeExpression(ExpressionTranslator.java:445)
	at org.jpmml.sklearn.ExpressionTranslator.AdditiveExpression(ExpressionTranslator.java:401)
	at org.jpmml.sklearn.ExpressionTranslator.ComparisonExpression(ExpressionTranslator.java:341)
	at org.jpmml.sklearn.ExpressionTranslator.NegationExpression(ExpressionTranslator.java:297)
	at org.jpmml.sklearn.ExpressionTranslator.LogicalAndExpression(ExpressionTranslator.java:267)
	at org.jpmml.sklearn.ExpressionTranslator.LogicalOrExpression(ExpressionTranslator.java:246)
	at org.jpmml.sklearn.ExpressionTranslator.IfElseExpression(ExpressionTranslator.java:227)
	at org.jpmml.sklearn.ExpressionTranslator.Expression(ExpressionTranslator.java:220)
	at org.jpmml.sklearn.ExpressionTranslator.Arguments(ExpressionTranslator.java:668)
	at org.jpmml.sklearn.ExpressionTranslator.FunctionInvocationExpression(ExpressionTranslator.java:641)
	at org.jpmml.sklearn.ExpressionTranslator.PrimaryExpression(ExpressionTranslator.java:537)
	at org.jpmml.sklearn.ExpressionTranslator.UnaryExpression(ExpressionTranslator.java:503)
	at org.jpmml.sklearn.ExpressionTranslator.MultiplicativeExpression(ExpressionTranslator.java:445)
	at org.jpmml.sklearn.ExpressionTranslator.AdditiveExpression(ExpressionTranslator.java:401)
	at org.jpmml.sklearn.ExpressionTranslator.ComparisonExpression(ExpressionTranslator.java:341)
	at org.jpmml.sklearn.ExpressionTranslator.NegationExpression(ExpressionTranslator.java:297)
	at org.jpmml.sklearn.ExpressionTranslator.LogicalAndExpression(ExpressionTranslator.java:267)
	at org.jpmml.sklearn.ExpressionTranslator.LogicalOrExpression(ExpressionTranslator.java:246)
	at org.jpmml.sklearn.ExpressionTranslator.IfElseExpression(ExpressionTranslator.java:227)
	at org.jpmml.sklearn.ExpressionTranslator.Expression(ExpressionTranslator.java:220)
	at org.jpmml.sklearn.ExpressionTranslator.Arguments(ExpressionTranslator.java:654)
	at org.jpmml.sklearn.ExpressionTranslator.FunctionInvocationExpression(ExpressionTranslator.java:641)
	at org.jpmml.sklearn.ExpressionTranslator.PrimaryExpression(ExpressionTranslator.java:537)
	at org.jpmml.sklearn.ExpressionTranslator.UnaryExpression(ExpressionTranslator.java:503)
	at org.jpmml.sklearn.ExpressionTranslator.MultiplicativeExpression(ExpressionTranslator.java:445)
	at org.jpmml.sklearn.ExpressionTranslator.AdditiveExpression(ExpressionTranslator.java:401)
	at org.jpmml.sklearn.ExpressionTranslator.ComparisonExpression(ExpressionTranslator.java:341)
	at org.jpmml.sklearn.ExpressionTranslator.NegationExpression(ExpressionTranslator.java:297)
	at org.jpmml.sklearn.ExpressionTranslator.LogicalAndExpression(ExpressionTranslator.java:267)
	at org.jpmml.sklearn.ExpressionTranslator.LogicalOrExpression(ExpressionTranslator.java:246)
	at org.jpmml.sklearn.ExpressionTranslator.IfElseExpression(ExpressionTranslator.java:227)
	at org.jpmml.sklearn.ExpressionTranslator.Expression(ExpressionTranslator.java:220)
	at org.jpmml.sklearn.ExpressionTranslator.translateExpressionInternal(ExpressionTranslator.java:214)
	at org.jpmml.sklearn.ExpressionTranslator.translate(ExpressionTranslator.java:74)
	at org.jpmml.sklearn.ExpressionTranslator.translate(ExpressionTranslator.java:63)
	at sklearn2pmml.preprocessing.ExpressionTransformer.encodeFeatures(ExpressionTransformer.java:47)
	at sklearn2pmml.decoration.Alias.encodeFeatures(Alias.java:56)
	at sklearn.Transformer.updateAndEncodeFeatures(Transformer.java:118)
	at sklearn_pandas.DataFrameMapper.initializeFeatures(DataFrameMapper.java:73)
	at sklearn.Initializer.encodeFeatures(Initializer.java:44)
	at sklearn.Transformer.updateAndEncodeFeatures(Transformer.java:118)
	at sklearn.Composite.encodeFeatures(Composite.java:129)
	at sklearn2pmml.pipeline.PMMLPipeline.encodePMML(PMMLPipeline.java:208)
	at org.jpmml.sklearn.Main.run(Main.java:228)
	at org.jpmml.sklearn.Main.main(Main.java:148)
```

**Comment by vruusmann** [comment]
> The numpy.clip func is also not supported and yes I can easily replace it with:
np.maximum(a_min, np.minimum(a, a_max))

I did saw that your expression was also using the `numpy.clip` UFunc, which is worthy of raising a separate issue.

As always, if some UFunc is not supported directly, then you should try expressing it in terms of already supported UFuncs. And if simpler UFuncs prove to be inadequate, then fall back to manual computation.

`numpy.minimum` and `numpy.maximum` are currently unsupported, because they are multi-arity methods. There is still some groundwork missing for them, so I've raised a separate issue #135 that you can track.

> java.lang.IllegalArgumentException
>   at org.jpmml.sklearn.ExpressionTranslator.translateFunction(ExpressionTranslator.java:180)

If you check the source code of `org.jpmml.sklearn.ExpressionTranslator`, then you'll see that the failing check is `if(arguments.size() != 1){ throw new IllegalArgumentException() }` - it's this very same multi-arity UFunc support thing.

**Comment by vruusmann** [comment]
@akhnatal You should replace unsupported `numpy.minimum` and `numpy.maximum` UFuncs with plain `if` statements.

For example, `numpy.minimum` should become: `X[0] if X[0] < X[1] else X[1]`.

**Comment by akhnatal** [comment]
Thanks for your great explanation and awesome work, and sorry for my poor understanding.
