### ISSUE TITLE
`FunctionTransformer` serialization in `DataFrameMapper` failing on `numpy.log`

### ISSUE THREAD

**Issue by jrwalk** [jpmml/jpmml-sklearn#15]
when using the `log` ufunc in the `FunctionTransformer` preprocessing option within a `DataFrameMapper`, the conversion to PMML now fails:

```
SEVERE: Failed to convert DataFrameMapper
java.lang.IllegalArgumentException: statsmodels.datasets.anes96.data
	at sklearn.preprocessing.FunctionTransformer.parseUFunc(FunctionTransformer.java:102)
	at sklearn.preprocessing.FunctionTransformer.encodeFeatures(FunctionTransformer.java:57)
	at sklearn_pandas.DataFrameMapper.encodeFeatures(DataFrameMapper.java:70)
	at org.jpmml.sklearn.Main.run(Main.java:146)
	at org.jpmml.sklearn.Main.main(Main.java:107)

Exception in thread "main" java.lang.IllegalArgumentException: statsmodels.datasets.anes96.data
	at sklearn.preprocessing.FunctionTransformer.parseUFunc(FunctionTransformer.java:102)
	at sklearn.preprocessing.FunctionTransformer.encodeFeatures(FunctionTransformer.java:57)
	at sklearn_pandas.DataFrameMapper.encodeFeatures(DataFrameMapper.java:70)
	at org.jpmml.sklearn.Main.run(Main.java:146)
	at org.jpmml.sklearn.Main.main(Main.java:107)
```

evidently due to a dependency on `statsmodels`?  Interestingly, the process still works with the `log10` ufunc.

**Comment by vruusmann** [comment]
An ufunc is identified by a combination of `module` and `name` attributes. The list of "supported" modules includes `numpy`, `numpy.core.numeric` and `numpy.lib.function_base`:
https://github.com/jpmml/jpmml-sklearn/blob/master/src/main/java/sklearn/preprocessing/FunctionTransformer.java#L84

How does the `statsmodels` module fit in here? How is it related to NumPy?

And the typical questions:
1. What is your Python version?
2. What is your NumPy version?

**Comment by jrwalk** [comment]
numpy version 1.11.1, python version 3.5.2.  The `FunctionTransformer` object is encoding the `numpy.log` function, which has previously worked (though I suspect I've update `numpy` since then).  I'm basing the `statsmodels

**Comment by vruusmann** [comment]
Can you avoid the `statsmodels` dependency if you explicitly import the `log` function from one of the above "supported" modules?

Something like `from numpy.core(.numeric) import log`

**Comment by jrwalk** [comment]
tested, still throws the same error with an explicit `log` import (previously was simply `import numpy` -> `numpy.log`)
