### ISSUE TITLE
Support for PyCaret transformers

### ISSUE THREAD

**Issue by szymoonl** [jpmml/jpmml-sklearn#175]
According to this [comment](https://github.com/pycaret/pycaret/issues/345#issuecomment-671089255), I tried to convert Pycaret model as follow:

```
prep_pipe = get_config('prep_pipe')
dt = create_model('dt')
final_dt = finalize_model(dt)

from sklearn2pmml.pipeline import PMMLPipeline

pmml_pipeline = PMMLPipeline([
	("prep_pipe", prep_pipe),
	("final_model", final_dt )
])

import pickle

with open("test_pmml.pkl", "wb") as pf:
	pickle.dump(pmml_pipeline, pf)
```
sklearn: 0.23.2
sklearn pandas: 2.2.0
sklearn2pmml: 0.84.1
pycaret: 2.3.6
openjdk version "11.0.15" 2022-04-19

The following exception occurred during conversion using a .jar:
> java -jar /jpmml-sklearn/pmml-sklearn-example/target/pmml-sklearn-example-executable-1.7-SNAPSHOT.jar --pkl-input /test_pmml.pkl --pmml-output model_pmml.pmml
Jun 21, 2022 8:06:26 AM org.jpmml.sklearn.example.Main run
INFO: Parsing PKL..
Jun 21, 2022 8:06:26 AM org.jpmml.sklearn.example.Main run
INFO: Parsed PKL in 57 ms.
Jun 21, 2022 8:06:26 AM org.jpmml.sklearn.example.Main run
INFO: Converting PKL to PMML..
Jun 21, 2022 8:06:26 AM sklearn2pmml.pipeline.PMMLPipeline initTargetFields
WARNING: Attribute 'sklearn2pmml.pipeline.PMMLPipeline.target_fields' is not set. Assuming y as the name of the target field
Jun 21, 2022 8:06:26 AM org.jpmml.sklearn.example.Main run
SEVERE: Failed to convert PKL to PMML
java.lang.IllegalArgumentException: The transformer object (Python class pycaret.internal.preprocess.DataTypes_Auto_infer) is not a supported Transformer
        at org.jpmml.python.CastFunction.apply(CastFunction.java:47)
        at sklearn.pipeline.Pipeline$1.apply(Pipeline.java:108)
        at sklearn.pipeline.Pipeline$1.apply(Pipeline.java:95)
        at com.google.common.collect.Lists$TransformingRandomAccessList.get(Lists.java:638)
        at sklearn2pmml.pipeline.PMMLPipeline.getHead(PMMLPipeline.java:629)
        at sklearn2pmml.pipeline.PMMLPipeline.getHead(PMMLPipeline.java:642)
        at sklearn2pmml.pipeline.PMMLPipeline.encodePMML(PMMLPipeline.java:198)
        at org.jpmml.sklearn.example.Main.run(Main.java:226)
        at org.jpmml.sklearn.example.Main.main(Main.java:151)
Caused by: java.lang.ClassCastException: Cannot cast net.razorvine.pickle.objects.ClassDict to sklearn.Transformer
        at java.base/java.lang.Class.cast(Class.java:3605)
        at org.jpmml.python.CastFunction.apply(CastFunction.java:45)
        ... 8 more

> Exception in thread "main" java.lang.IllegalArgumentException: The transformer object (Python class pycaret.internal.preprocess.DataTypes_Auto_infer) is not a supported Transformer
        at org.jpmml.python.CastFunction.apply(CastFunction.java:47)
        at sklearn.pipeline.Pipeline$1.apply(Pipeline.java:108)
        at sklearn.pipeline.Pipeline$1.apply(Pipeline.java:95)
        at com.google.common.collect.Lists$TransformingRandomAccessList.get(Lists.java:638)
        at sklearn2pmml.pipeline.PMMLPipeline.getHead(PMMLPipeline.java:629)
        at sklearn2pmml.pipeline.PMMLPipeline.getHead(PMMLPipeline.java:642)
        at sklearn2pmml.pipeline.PMMLPipeline.encodePMML(PMMLPipeline.java:198)
        at org.jpmml.sklearn.example.Main.run(Main.java:226)
        at org.jpmml.sklearn.example.Main.main(Main.java:151)
Caused by: java.lang.ClassCastException: Cannot cast net.razorvine.pickle.objects.ClassDict to sklearn.Transformer
        at java.base/java.lang.Class.cast(Class.java:3605)
        at org.jpmml.python.CastFunction.apply(CastFunction.java:45)
        ... 8 more

How to solve this? 🤔
Thank you in advance!

**Comment by szymoonl** [comment]
When trying to convert the model alone without preprocessing, the following error appears:

> Aug 16, 2022 12:48:12 PM org.jpmml.sklearn.example.Main run
INFO: Parsing PKL..
Aug 16, 2022 12:48:12 PM org.jpmml.sklearn.example.Main run
SEVERE: Failed to parse PKL
net.razorvine.pickle.PickleException: failed to __setstate__()
        at net.razorvine.pickle.Unpickler.load_build(Unpickler.java:395)
        at net.razorvine.pickle.Unpickler.dispatch(Unpickler.java:220)
        at org.jpmml.python.CustomUnpickler.dispatch(CustomUnpickler.java:31)
        at org.jpmml.python.PickleUtil$1.dispatch(PickleUtil.java:64)
        at net.razorvine.pickle.Unpickler.load(Unpickler.java:109)
        at org.jpmml.python.PickleUtil.unpickle(PickleUtil.java:85)
        at org.jpmml.sklearn.example.Main.run(Main.java:163)
        at org.jpmml.sklearn.example.Main.main(Main.java:151)
> Caused by: java.lang.NoSuchMethodException: net.razorvine.pickle.objects.ClassDict.__setstate__(java.lang.Integer)
        at java.base/java.lang.Class.getMethod(Class.java:2108)
        at net.razorvine.pickle.Unpickler.load_build(Unpickler.java:392)
        ... 7 more

> Exception in thread "main" net.razorvine.pickle.PickleException: failed to __setstate__()
        at net.razorvine.pickle.Unpickler.load_build(Unpickler.java:395)
        at net.razorvine.pickle.Unpickler.dispatch(Unpickler.java:220)
        at org.jpmml.python.CustomUnpickler.dispatch(CustomUnpickler.java:31)
        at org.jpmml.python.PickleUtil$1.dispatch(PickleUtil.java:64)
        at net.razorvine.pickle.Unpickler.load(Unpickler.java:109)
        at org.jpmml.python.PickleUtil.unpickle(PickleUtil.java:85)
        at org.jpmml.sklearn.example.Main.run(Main.java:163)
        at org.jpmml.sklearn.example.Main.main(Main.java:151)
> Caused by: java.lang.NoSuchMethodException: net.razorvine.pickle.objects.ClassDict.__setstate__(java.lang.Integer)
        at java.base/java.lang.Class.getMethod(Class.java:2108)
        at net.razorvine.pickle.Unpickler.load_build(Unpickler.java:392)
        ... 7 more

The model is a random forest but trained with GPU, so it is a cuml object:

` RandomForestClassifier() `
` <class 'cuml.ensemble.randomforestclassifier.RandomForestClassifier'>`

Converting the model alone without GPU as a sklearn object works without problem. 🤔
</br></br>
When converting model with preprocessing pipeline I got below exception:

> Aug 16, 2022 12:48:32 PM org.jpmml.sklearn.example.Main run
INFO: Parsing PKL..
Aug 16, 2022 12:48:32 PM org.jpmml.sklearn.example.Main run
SEVERE: Failed to parse PKL
net.razorvine.pickle.PickleException: failed to __setstate__()
        at net.razorvine.pickle.Unpickler.load_build(Unpickler.java:395)
        at net.razorvine.pickle.Unpickler.dispatch(Unpickler.java:220)
        at org.jpmml.python.CustomUnpickler.dispatch(CustomUnpickler.java:31)
        at org.jpmml.python.PickleUtil$1.dispatch(PickleUtil.java:64)
        at net.razorvine.pickle.Unpickler.load(Unpickler.java:109)
        at org.jpmml.python.PickleUtil.unpickle(PickleUtil.java:85)
        at org.jpmml.sklearn.example.Main.run(Main.java:163)
        at org.jpmml.sklearn.example.Main.main(Main.java:151)
Caused by: java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at net.razorvine.pickle.Unpickler.load_build(Unpickler.java:393)
        ... 7 more
Caused by: net.razorvine.pickle.PickleException: Expected 8 attribute(s), got 9 attribute(s)
        at org.jpmml.python.CustomPythonObject.createAttributeMap(CustomPythonObject.java:81)
        at numpy.DType.__setstate__(DType.java:50)
        ... 12 more

> Exception in thread "main" net.razorvine.pickle.PickleException: failed to __setstate__()
        at net.razorvine.pickle.Unpickler.load_build(Unpickler.java:395)
        at net.razorvine.pickle.Unpickler.dispatch(Unpickler.java:220)
        at org.jpmml.python.CustomUnpickler.dispatch(CustomUnpickler.java:31)
        at org.jpmml.python.PickleUtil$1.dispatch(PickleUtil.java:64)
        at net.razorvine.pickle.Unpickler.load(Unpickler.java:109)
        at org.jpmml.python.PickleUtil.unpickle(PickleUtil.java:85)
        at org.jpmml.sklearn.example.Main.run(Main.java:163)
        at org.jpmml.sklearn.example.Main.main(Main.java:151)
Caused by: java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at net.razorvine.pickle.Unpickler.load_build(Unpickler.java:393)
        ... 7 more
Caused by: net.razorvine.pickle.PickleException: Expected 8 attribute(s), got 9 attribute(s)
        at org.jpmml.python.CustomPythonObject.createAttributeMap(CustomPythonObject.java:81)
        at numpy.DType.__setstate__(DType.java:50)
        ... 12 more

**Comment by vruusmann** [comment]
@szymoonl Please open a new issue for each unsupported ML framework.

Otherwise I'll classify all your messages as "spam", and send to trash.
