### ISSUE TITLE
VotingClassifier failure

### ISSUE THREAD

**Issue by bkellerman** [jpmml/jpmml-sklearn#23]
I'm getting an error when running sklearn2pmml() on an sklearn VotingClassifier.

Here is the code:
```
gb_1 = GradientBoostingClassifier(n_estimators=n_est_ens)
ext_1 = ExtraTreesClassifier(n_estimators=n_est_ens, criterion='gini', max_features='sqrt')
ext_2 = ExtraTreesClassifier(n_estimators=n_est_ens, criterion='entropy', max_features='log2')
rf_1 = RandomForestClassifier(n_estimators=n_est_ens, criterion='gini', random_state=randint(1,10000))
rf_2 = RandomForestClassifier(n_estimators=n_est_ens, criterion='entropy', random_state=randint(1,10000))
clf = VotingClassifier(estimators=[ ('gb_1', gb_1), ('ext_1', ext_1), ('ext_2', ext_2), ('rf_1', rf_1), ('rf_2', rf_2)], voting=voting, weights=[3,1,1,1,1])

clf.fit(X_train, y_train)
sklearn2pmml(clf, None, pmml_file, with_repr = False, debug = True)
```

Here is the error:
```
('python: ', '2.7.12')
('sklearn: ', '0.18.1')
('sklearn.externals.joblib:', '0.10.3')
('sklearn_pandas: ', '1.1.0')
('sklearn2pmml: ', '0.12.1')
java -cp ~/.local/lib/python2.7/site-packages/sklearn2pmml/resources/guava-19.0.jar:~/.local/lib/python2.7/site-packages/sklearn2pmml/resources/jaxb-core-2.2.11.jar:~/.local/lib/python2.7/site-packages/sklearn2pmml/resources/pyrolite-4.14.jar:~/.local/lib/python2.7/site-packages/sklearn2pmml/resources/slf4j-api-1.7.21.jar:~/.local/lib/python2.7/site-packages/sklearn2pmml/resources/slf4j-jdk14-1.7.21.jar:~/.local/lib/python2.7/site-packages/sklearn2pmml/resources/jaxb-runtime-2.2.11.jar:~/.local/lib/python2.7/site-packages/sklearn2pmml/resources/pmml-model-metro-1.3.3.jar:~/.local/lib/python2.7/site-packages/sklearn2pmml/resources/jpmml-converter-1.1.1.jar:~/.local/lib/python2.7/site-packages/sklearn2pmml/resources/serpent-1.15.jar:~/.local/lib/python2.7/site-packages/sklearn2pmml/resources/istack-commons-runtime-2.21.jar:~/.local/lib/python2.7/site-packages/sklearn2pmml/resources/pmml-model-1.3.3.jar:~/.local/lib/python2.7/site-packages/sklearn2pmml/resources/pmml-schema-1.3.3.jar:~/.local/lib/python2.7/site-packages/sklearn2pmml/resources/jpmml-xgboost-1.1.1.jar:~/.local/lib/python2.7/site-packages/sklearn2pmml/resources/jcommander-1.48.jar:~/.local/lib/python2.7/site-packages/sklearn2pmml/resources/jpmml-sklearn-1.1.4.jar:~/.local/lib/python2.7/site-packages/sklearn2pmml/resources/pmml-agent-1.3.3.jar org.jpmml.sklearn.Main --pkl-estimator-input /tmp/estimator-XOBeGz.pkl.z --pmml-output RF200.pmml
Dec 09, 2016 3:48:19 PM org.jpmml.sklearn.Main run
INFO: Parsing Estimator PKL..
Dec 09, 2016 3:48:19 PM org.jpmml.sklearn.Main run
INFO: Parsed Estimator PKL in 35 ms.
Exception in thread "main" java.lang.IllegalArgumentException: The estimator object (Python class numpy.ndarray) is not an Estimator or is not a supported Estimator subclass
	at org.jpmml.sklearn.Main.run(Main.java:180)
	at org.jpmml.sklearn.Main.main(Main.java:107)
('Preserved joblib dump file(s): ', '/tmp/estimator-XOBeGz.pkl.z')
Traceback (most recent call last):
  File "grid_search.py", line 251, in <module>
    sklearn2pmml(clf, None, pmml_file, with_repr = False, debug = True)
  File "~/.local/lib/python2.7/site-packages/sklearn2pmml/__init__.py", line 65, in sklearn2pmml
    subprocess.check_call(cmd)
  File "/usr/lib/python2.7/subprocess.py", line 541, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['java', '-cp', '~/.local/lib/python2.7/site-packages/sklearn2pmml/resources/guava-19.0.jar:~/.local/lib/python2.7/site-packages/sklearn2pmml/resources/jaxb-core-2.2.11.jar:~/.local/lib/python2.7/site-packages/sklearn2pmml/resources/pyrolite-4.14.jar:~/.local/lib/python2.7/site-packages/sklearn2pmml/resources/slf4j-api-1.7.21.jar:~/.local/lib/python2.7/site-packages/sklearn2pmml/resources/slf4j-jdk14-1.7.21.jar:~/.local/lib/python2.7/site-packages/sklearn2pmml/resources/jaxb-runtime-2.2.11.jar:~/.local/lib/python2.7/site-packages/sklearn2pmml/resources/pmml-model-metro-1.3.3.jar:~/.local/lib/python2.7/site-packages/sklearn2pmml/resources/jpmml-converter-1.1.1.jar:~/.local/lib/python2.7/site-packages/sklearn2pmml/resources/serpent-1.15.jar:~/.local/lib/python2.7/site-packages/sklearn2pmml/resources/istack-commons-runtime-2.21.jar:~/.local/lib/python2.7/site-packages/sklearn2pmml/resources/pmml-model-1.3.3.jar:~/.local/lib/python2.7/site-packages/sklearn2pmml/resources/pmml-schema-1.3.3.jar:~/.local/lib/python2.7/site-packages/sklearn2pmml/resources/jpmml-xgboost-1.1.1.jar:~/.local/lib/python2.7/site-packages/sklearn2pmml/resources/jcommander-1.48.jar:~/.local/lib/python2.7/site-packages/sklearn2pmml/resources/jpmml-sklearn-1.1.4.jar:~/.local/lib/python2.7/site-packages/sklearn2pmml/resources/pmml-agent-1.3.3.jar', 'org.jpmml.sklearn.Main', '--pkl-estimator-input', '/tmp/estimator-XOBeGz.pkl.z', '--pmml-output', 'RF200.pmml']' returned non-zero exit status 1
```

**Comment by vruusmann** [comment]
> Exception in thread "main" java.lang.IllegalArgumentException: The estimator object (Python class numpy.ndarray) is not an Estimator or is not a supported Estimator subclass

It appears that Java class `sklearn.ensemble.voting_classifier.VotingClassifier` is unable to correctly "unpack" the list of member estimators.

JPMML-SkLearn has integration tests for this model types, and they pass cleanly:
https://github.com/jpmml/jpmml-sklearn/blob/master/src/test/resources/main.py#L150
https://github.com/jpmml/jpmml-sklearn/blob/master/src/test/resources/main.py#L243

The only difference between my code and your code is that my code does not spell out the argument name "estimators". Does the situation improve if you leave it out in your code too?

> ('Preserved joblib dump file(s): ', '/tmp/estimator-XOBeGz.pkl.z')

Do you have the joblib dump file `/tmp/estimator-XOBeGz.pkl.z` still around? I'd like to take a look into it.

**Comment by vruusmann** [comment]
I can reproduce this failure locally. Will investigate and fix.

**Comment by vruusmann** [comment]
It appears to be the case that `joblib.dump()` is wrapping the `clf` object into a Numpy array. JPMML-SkLearn expects a "raw" Estimator object, not a "wrapped" one, hence the IllegalArgumentException.

The conversion works OK if `joblib.dump()` is replaced with `pickle.dump()`. Will have to investigate why Joblib is doing that, could be some new "feature".

Here's my environment:
```
('python: ', '2.7.11')
('sklearn: ', '0.18')
('sklearn.externals.joblib:', '0.10.2')
('sklearn_pandas: ', '1.2.0')
('sklearn2pmml: ', '0.12.1')
```

Also, deleted my earlier comment, which was completely wrong.

**Comment by jwang2sc** [comment]
Hi, I've been experiencing the same error, here is my code block:

```
from sklearn2pmml import sklearn2pmml

sklearn2pmml(estimator=model,
             mapper=mapper,
             pmml="a.pmml", 
             debug = True)
```

and here is the error message
```

('python: ', '2.7.9')
('sklearn: ', '0.18')
('sklearn.externals.joblib:', '0.10.2')
('sklearn_pandas: ', '1.2.0')
('sklearn2pmml: ', '0.12.1')
java -cp /usr/local/lib/python2.7/dist-packages/sklearn2pmml/resources/jpmml-sklearn-1.1.4.jar:/usr/local/lib/python2.7/dist-packages/sklearn2pmml/resources/pmml-model-metro-1.3.3.jar:/usr/local/lib/python2.7/dist-packages/sklearn2pmml/resources/serpent-1.15.jar:/usr/local/lib/python2.7/dist-packages/sklearn2pmml/resources/jaxb-runtime-2.2.11.jar:/usr/local/lib/python2.7/dist-packages/sklearn2pmml/resources/pmml-schema-1.3.3.jar:/usr/local/lib/python2.7/dist-packages/sklearn2pmml/resources/pyrolite-4.14.jar:/usr/local/lib/python2.7/dist-packages/sklearn2pmml/resources/jpmml-xgboost-1.1.1.jar:/usr/local/lib/python2.7/dist-packages/sklearn2pmml/resources/slf4j-jdk14-1.7.21.jar:/usr/local/lib/python2.7/dist-packages/sklearn2pmml/resources/jpmml-converter-1.1.1.jar:/usr/local/lib/python2.7/dist-packages/sklearn2pmml/resources/pmml-model-1.3.3.jar:/usr/local/lib/python2.7/dist-packages/sklearn2pmml/resources/slf4j-api-1.7.21.jar:/usr/local/lib/python2.7/dist-packages/sklearn2pmml/resources/jaxb-core-2.2.11.jar:/usr/local/lib/python2.7/dist-packages/sklearn2pmml/resources/pmml-agent-1.3.3.jar:/usr/local/lib/python2.7/dist-packages/sklearn2pmml/resources/jcommander-1.48.jar:/usr/local/lib/python2.7/dist-packages/sklearn2pmml/resources/guava-19.0.jar:/usr/local/lib/python2.7/dist-packages/sklearn2pmml/resources/istack-commons-runtime-2.21.jar org.jpmml.sklearn.Main --pkl-estimator-input /tmp/estimator-p3SV9Q.pkl.z --pkl-mapper-input /tmp/mapper-IeShOd.pkl.z --pmml-output /Users/jianqiang.wang/src/snapchat/datascience/unlockables/geofilter_conversion_benchmark/a.pmml
('Preserved joblib dump file(s): ', '/tmp/estimator-p3SV9Q.pkl.z /tmp/mapper-IeShOd.pkl.z')

CalledProcessErrorTraceback (most recent call last)
<ipython-input-39-1705bb6b7573> in <module>()
      4              mapper=mapper,
      5              pmml="/Users/jianqiang.wang/src/snapchat/datascience/unlockables/geofilter_conversion_benchmark/a.pmml",
----> 6              debug = True)

/usr/local/lib/python2.7/dist-packages/sklearn2pmml/__init__.pyc in sklearn2pmml(estimator, mapper, pmml, with_repr, debug)
     63                 if(debug):
     64                         print(" ".join(cmd))
---> 65                 subprocess.check_call(cmd)
     66         finally:
     67                 if(debug):

/usr/lib/python2.7/subprocess.pyc in check_call(*popenargs, **kwargs)
    538         if cmd is None:
    539             cmd = popenargs[0]
--> 540         raise CalledProcessError(retcode, cmd)
    541     return 0
    542 

CalledProcessError: Command '['java', '-cp', '/usr/local/lib/python2.7/dist-packages/sklearn2pmml/resources/jpmml-sklearn-1.1.4.jar:/usr/local/lib/python2.7/dist-packages/sklearn2pmml/resources/pmml-model-metro-1.3.3.jar:/usr/local/lib/python2.7/dist-packages/sklearn2pmml/resources/serpent-1.15.jar:/usr/local/lib/python2.7/dist-packages/sklearn2pmml/resources/jaxb-runtime-2.2.11.jar:/usr/local/lib/python2.7/dist-packages/sklearn2pmml/resources/pmml-schema-1.3.3.jar:/usr/local/lib/python2.7/dist-packages/sklearn2pmml/resources/pyrolite-4.14.jar:/usr/local/lib/python2.7/dist-packages/sklearn2pmml/resources/jpmml-xgboost-1.1.1.jar:/usr/local/lib/python2.7/dist-packages/sklearn2pmml/resources/slf4j-jdk14-1.7.21.jar:/usr/local/lib/python2.7/dist-packages/sklearn2pmml/resources/jpmml-converter-1.1.1.jar:/usr/local/lib/python2.7/dist-packages/sklearn2pmml/resources/pmml-model-1.3.3.jar:/usr/local/lib/python2.7/dist-packages/sklearn2pmml/resources/slf4j-api-1.7.21.jar:/usr/local/lib/python2.7/dist-packages/sklearn2pmml/resources/jaxb-core-2.2.11.jar:/usr/local/lib/python2.7/dist-packages/sklearn2pmml/resources/pmml-agent-1.3.3.jar:/usr/local/lib/python2.7/dist-packages/sklearn2pmml/resources/jcommander-1.48.jar:/usr/local/lib/python2.7/dist-packages/sklearn2pmml/resources/guava-19.0.jar:/usr/local/lib/python2.7/dist-packages/sklearn2pmml/resources/istack-commons-runtime-2.21.jar', 'org.jpmml.sklearn.Main', '--pkl-estimator-input', '/tmp/estimator-p3SV9Q.pkl.z', '--pkl-mapper-input', '/tmp/mapper-IeShOd.pkl.z', '--pmml-output', u'/Users/jianqiang.wang/src/snapchat/datascience/unlockables/geofilter_conversion_benchmark/a.pmml']' returned non-zero exit status 1

```

**Comment by vruusmann** [comment]
@jwang2sc How do you know it is the same error? You're showing me the Python exception (a generic `CalledProcessError`, does not contain any actionable information), but not the Java exception (contains all the actionable information).

Besides, you're using an outdated `sklearn2pmml` package version.

**Comment by vruusmann** [comment]
Closing as stale.

Life has moved on from Python 2.7 to 3.10+, plus it's now possible to dump Pipelines in Joblib- and Dill-flavoured Pickle data formats (in case the plain Pickle data format is too limiting).
