### ISSUE TITLE
OneHotEncoder parsing failure

### ISSUE THREAD

**Issue by christophe-rannou** [jpmml/jpmml-sklearn#37]
It seems that the OneHotEncoder parsing fails for an unknown reason. Maybe I am using it wrong. My pipeline is as follows : 
 ```
categorical_features=[1,2,3,4]
oh_encoder = sklearn.preprocessing.OneHotEncoder(categorical_features=categorical_features)
rfc = sklearn.ensemble.RandomForestClassifier(n_estimators=100, min_samples_leaf=20)
pipeline = PMMLPipeline([
    ("encoder", oh_encoder),
    ("classifier", rfc)
])
fraud_pipeline.fit(X,y)
joblib.dump(pipeline, "ohe_rfc_pipeline.pkl.z", compress=9)
```
I then go through the converter jar and get the following error:
```
Exception in thread "main" java.lang.IllegalArgumentException: Expected 1 element(s), got 4 element(s)
	at org.jpmml.sklearn.ClassDictUtil.checkSize(ClassDictUtil.java:136)
	at sklearn.preprocessing.OneHotEncoder.getValues(OneHotEncoder.java:103)
	at sklearn.preprocessing.OneHotEncoder.getDataType(OneHotEncoder.java:52)
	at sklearn2pmml.PMMLPipeline.encodePMML(PMMLPipeline.java:115)
	at org.jpmml.sklearn.Main.run(Main.java:146)
	at org.jpmml.sklearn.Main.main(Main.java:93)
```

If I set the oneHotEncoder with only one categorical feature (instaed of 4) the error becomes : 
```
Exception in thread "main" java.lang.ClassCastException: sklearn.preprocessing.OneHotEncoder cannot be cast to sklearn.HasNumberOfFeatures
	at sklearn2pmml.PMMLPipeline.initFeatures(PMMLPipeline.java:153)
	at sklearn2pmml.PMMLPipeline.encodePMML(PMMLPipeline.java:115)
	at org.jpmml.sklearn.Main.run(Main.java:146)
	at org.jpmml.sklearn.Main.main(Main.java:93)
```

Maybe I am missing something in my use of the oneHotEncoder ?

**Comment by vruusmann** [comment]
You need to reorganize your Python code, so that it would be easier to understand for the SkLearn2PMML conversion tool:

- The first step of the pipeline should be [`sklearn_pandas.DataFrameMapper`](https://github.com/paulgb/sklearn-pandas#usage), which specifies the number and names of input fields (this would take care of the `java.lang.ClassCastException`).
- Inside the `DataFrameMapper`, please map every categorical column to a separate `sklearn.preprocessing.OneHotEncoder` transformer instance (this would take care of the `java.lang.IllegalArgumentException`).

Something like this:
```Python
categorical_columns = [..]

mapper = DataFrameMapper(
  [(categorical_column, OneHotEncoder()) for categorical_column in categorical_columns]
)
classifier = RandomForestClassifier()

pipeline = PMMLPipeline([
  ("mapper", mapper),
  ("classifier", classifier)
])
pipeline.fit(df, df["target"])
```

**Comment by christophe-rannou** [comment]
Thanks it worked fine (except that OnehotEncoder expects a 2darray then it should be `([categorical_column], OneHotEncoder())`) in the mapper.
