### ISSUE TITLE
Using more than one CountVectorizer in DataFrameMapper gives error

### ISSUE THREAD

**Issue by mohitbadwal** [jpmml/jpmml-sklearn#43]
I am trying to use more than one countvectorizer in DataFrameMapper and its giving an error . 

`DataFrameMapper([('attachment_links',countVectorizer2),('meta_email_subject',countVectorizer1)])
`
Although when I use a single CountVectorizer then there's no issue.
here the stacktrace-
```
Jul 20, 2017 5:38:55 PM org.jpmml.sklearn.Main run
INFO: Parsed PKL in 785 ms.
Jul 20, 2017 5:38:55 PM org.jpmml.sklearn.Main run
INFO: Converting..
 at sklearn.pipeline.Pipeline.encodeFeatures(Pipeline.java:93)
 at sklearn2pmml.PMMLPipeline.encodePMML(PMMLPipeline.java:122)
 at org.jpmml.sklearn.Main.run(Main.java:144)
 at org.jpmml.sklearn.Main.main(Main.java:93)
java.lang.IllegalArgumentException: tf
 at org.jpmml.converter.PMMLEncoder.addDefineFunction(PMMLEncoder.java:215)
 at sklearn.feature_extraction.text.CountVectorizer.encodeFeatures(CountVectorizer.java:126)
 at sklearn_pandas.DataFrameMapper.initializeFeatures(DataFrameMapper.java:74)
 at sklearn.Initializer.encodeFeatures(Initializer.java:53)
Jul 20, 2017 5:38:55 PM org.jpmml.sklearn.Main run
SEVERE: Failed to convert
java.lang.IllegalArgumentException: tf
 at org.jpmml.converter.PMMLEncoder.addDefineFunction(PMMLEncoder.java:215)
 at sklearn.feature_extraction.text.CountVectorizer.encodeFeatures(CountVectorizer.java:126)
 at sklearn_pandas.DataFrameMapper.initializeFeatures(DataFrameMapper.java:74)
 at sklearn.Initializer.encodeFeatures(Initializer.java:53)
 at sklearn.pipeline.Pipeline.encodeFeatures(Pipeline.java:93)
 at sklearn2pmml.PMMLPipeline.encodePMML(PMMLPipeline.java:122)
 at org.jpmml.sklearn.Main.run(Main.java:144)
 at org.jpmml.sklearn.Main.main(Main.java:93)
```

**Comment by vruusmann** [comment]
The solution is to generate a unique name for each `DefineFunction` element here:
https://github.com/jpmml/jpmml-sklearn/blob/master/src/main/java/sklearn/feature_extraction/text/CountVectorizer.java#L204

For example, "tf" could simply be replaced with `"tf-" + String.valueOf(System.currentTimeMillis())`.

I wasn't expecting anyone to hit this "limit".

**Comment by mohitbadwal** [comment]
I'll try and get back to you if there's any issue.

**Comment by mohitbadwal** [comment]
I tried the solution you gave , but it still gives the same error.

**Comment by vode** [comment]
I think you change it in a wrong way.
`Random ran = new Random();
		DefineFunction defineFunction = new DefineFunction("tf"+Integer.toString(ran.nextInt(100)), OpType.CONTINUOUS, null)
			.setDataType(DataType.DOUBLE)
			.addParameterFields(documentField, termField)
			.setExpression(textIndex);
`
would do that, this will generate a defineFunction with a unique name every time.
