### ISSUE TITLE
Fail to convert LightGBM model with categorical features

### ISSUE THREAD

**Issue by iezepov** [jpmml/jpmml-sklearn#67]
Hi!

Looks like it's impossible to convert LightGBm model with categorical variables in the trees.

Minimal step to reproduce:
```
from sklearn2pmml import PMMLPipeline, sklearn2pmml
import lightgbm as lgb
import pandas as pd
import numpy as np

pipe = PMMLPipeline([
    ('lgb', lgb.LGBMRegressor(min_data=1))  # min_data is needed because of small dataset
])

X = pd.DataFrame({'A': [1, 1, 2, 2, 3, 3], 'B': np.random.normal(size=6)})
y = pd.Series(np.random.normal(size=6))

pipe.fit(X, y)
sklearn2pmml(pipe, './x.pmml')  # This one runs ok

X['A'] = X['A'].astype('category')

pipe.fit(X, y)
sklearn2pmml(pipe, './x.pmml')  # This one fails
```

Error from python is not interesting:
```
RuntimeError: The JPMML-SkLearn conversion application has failed. The Java process should have printed more information about the failure into its standard output and/or error streams
```

And running java command directly gives you:
```
Jan 12, 2018 12:23:20 PM org.jpmml.sklearn.Main run
INFO: Parsing PKL..
Jan 12, 2018 12:23:20 PM org.jpmml.sklearn.Main run
INFO: Parsed PKL in 24 ms.
Jan 12, 2018 12:23:20 PM org.jpmml.sklearn.Main run
INFO: Converting..
Jan 12, 2018 12:23:20 PM sklearn2pmml.PMMLPipeline encodePMML
WARNING: The 'target_fields' attribute is not set. Assuming y as the name of the target field
Jan 12, 2018 12:23:21 PM org.jpmml.sklearn.Main run
SEVERE: Failed to convert
java.lang.IllegalArgumentException
	at org.jpmml.lightgbm.Tree.encodeNode(Tree.java:174)
	at org.jpmml.lightgbm.Tree.encodeTreeModel(Tree.java:96)
	at org.jpmml.lightgbm.ObjectiveFunction.createMiningModel(ObjectiveFunction.java:66)
	at org.jpmml.lightgbm.Regression.encodeMiningModel(Regression.java:49)
	at org.jpmml.lightgbm.GBDT.encodeMiningModel(GBDT.java:211)
	at lightgbm.sklearn.BoosterUtil.encodeModel(BoosterUtil.java:50)
	at lightgbm.sklearn.LGBMRegressor.encodeModel(LGBMRegressor.java:38)
	at lightgbm.sklearn.LGBMRegressor.encodeModel(LGBMRegressor.java:25)
	at sklearn2pmml.PMMLPipeline.encodePMML(PMMLPipeline.java:160)
	at org.jpmml.sklearn.Main.run(Main.java:144)
	at org.jpmml.sklearn.Main.main(Main.java:93)

Exception in thread "main" java.lang.IllegalArgumentException
	at org.jpmml.lightgbm.Tree.encodeNode(Tree.java:174)
	at org.jpmml.lightgbm.Tree.encodeTreeModel(Tree.java:96)
	at org.jpmml.lightgbm.ObjectiveFunction.createMiningModel(ObjectiveFunction.java:66)
	at org.jpmml.lightgbm.Regression.encodeMiningModel(Regression.java:49)
	at org.jpmml.lightgbm.GBDT.encodeMiningModel(GBDT.java:211)
	at lightgbm.sklearn.BoosterUtil.encodeModel(BoosterUtil.java:50)
	at lightgbm.sklearn.LGBMRegressor.encodeModel(LGBMRegressor.java:38)
	at lightgbm.sklearn.LGBMRegressor.encodeModel(LGBMRegressor.java:25)
	at sklearn2pmml.PMMLPipeline.encodePMML(PMMLPipeline.java:160)
	at org.jpmml.sklearn.Main.run(Main.java:144)
	at org.jpmml.sklearn.Main.main(Main.java:93)
```

My environment is:
```
java version: 1.8.0
Python 3.6.4
sklearn2pmml==0.29.0
lightgbm==2.0.12
```

**Comment by vruusmann** [comment]
The root cause of the exception is that `PMMLPipeline` has not been informed about this "data schema" change, so it's unable to prepare a properly customized `org.jpmml.converter.Schema` object instance.

The fix needs to be applied in Python code:
```Python
from sklearn_pandas import DataFrameMapper
from sklearn2pmml.decoration import CategoricalDomain, ContinuousDomain

pipe = PMMLPipeline([
	("mapper", DataFrameMapper([
		("A", CategoricalDomain()),
		("B", ContinuousDomain())
	])),
	("lgb", lgb.LGBMRegressor(min_data=1))
])
pipe.fit(X, y)
```

**Comment by iezepov** [comment]
Thank you!

**Comment by luobingting** [comment]
X = pd.DataFrame({'gender':[np.random.choice(["M","F"]) for i in range(1000)], 'B': np.random.normal(size=1000)})
y = pd.Series([np.random.choice([0,1]) for i in range(1000)])

X['gender'] = X['gender'].astype('category')

pipe = PMMLPipeline([
        ("mapper", DataFrameMapper([
            ("gender", CategoricalDomain()),
            ("B", ContinuousDomain())
        ])),
        ("lgb", lgb.LGBMClassifier(min_data=1))
    ])
pipe.fit(X, y)

as we know, lightGBM can solve category features, but when i do this, it get wrong,  why........
ValueError: could not convert string to float: 'F'

**Comment by vruusmann** [comment]
@luobingting The original issue was about a **categorical integer** column. You're dealing with a **categorical string** column, which is a totally different matter.

I did some experimentation, and the `category` column type works only if you pass it directly to the `LGBClassifier.fit(X, y)` method. If you wrap the LightGBM classifier into a Scikit-Learn pipeline, then the `(PMML)Pipeline.fit(X, y)` method appears to "cast" the `category` column type back to ordinary `str` column type, and the fitting fails.

As a side note - this is 100% LightGBM/Scikit-Learn issue, and is not related to the JPMML-LightGBM/JPMML-SkLearn in any way.

Also, next time, consider opening a new issue.
