### ISSUE TITLE
Failed to convert pipeline with error: "The first transformer or estimator object (Python class sklearn.feature_selection.univariate_selection.SelectKBest) does not specify feature type information_"

### ISSUE THREAD

**Issue by fjfjfan** [jpmml/jpmml-sklearn#78]
How to reproduce the problem:
**1. train the model and dump it to pkl**
```Python
import xgboost as xgb
import pickle
import numpy as np
from sklearn.model_selection import KFold, train_test_split, GridSearchCV
from sklearn.metrics import confusion_matrix, mean_squared_error
from sklearn.datasets import load_iris, load_digits, load_boston
import matplotlib.pyplot as plt
from sklearn import datasets
from sklearn.metrics import accuracy_score
from xgboost import XGBClassifier
from xgboost import XGBRegressor
from sklearn.feature_selection import SelectFromModel,SelectKBest
from sklearn.svm import LinearSVC
from sklearn.pipeline import Pipeline
from sklearn.externals import joblib

digits = datasets.load_digits()
X_train,X_test,y_train,y_test = train_test_split(digits.data,digits.target,test_size = 0.3,random_state = 33)

clf = Pipeline([
#   ('feature_selection', SelectFromModel(LinearSVC(penalty="l1"))),
  ('feature_selection', SelectKBest(k=10)),
  ('classification', XGBClassifier())
])
clf.fit(X_train, y_train)

fulfile = "feature_selection.pkl"
joblib.dump(clf, fulfile)
```
**2.use the jar to convert it** 
```
-bash-4.2$ java -jar jpmml-sklearn-executable-1.5-SNAPSHOT.jar --pkl-input  feature_selection.pkl --pmml-output feature_selection.xml
Aug 16, 2018 8:45:29 PM org.jpmml.sklearn.Main run
INFO: Parsing PKL..
Aug 16, 2018 8:45:29 PM org.jpmml.sklearn.Main run
INFO: Parsed PKL in 27 ms.
Aug 16, 2018 8:45:29 PM org.jpmml.sklearn.Main run
INFO: Converting..
Aug 16, 2018 8:45:29 PM sklearn2pmml.pipeline.PMMLPipeline encodePMML
WARNING: Attribute 'sklearn2pmml.PMMLPipeline.target_fields' is not set. Assuming y as the name of the target field
Aug 16, 2018 8:45:29 PM org.jpmml.sklearn.Main run
**_SEVERE: Failed to convert
java.lang.IllegalArgumentException: The first transformer or estimator object (Python class sklearn.feature_selection.univariate_selection.SelectKBest) does not specify feature type information_**
	at sklearn2pmml.pipeline.PMMLPipeline.encodePMML(PMMLPipeline.java:199)
	at org.jpmml.sklearn.Main.run(Main.java:145)
	at org.jpmml.sklearn.Main.main(Main.java:94)
Caused by: java.lang.UnsupportedOperationException
	at sklearn.MultiTransformer.getOpType(MultiTransformer.java:33)
	at sklearn2pmml.pipeline.PMMLPipeline.encodePMML(PMMLPipeline.java:189)
	... 2 more

Exception in thread "main" java.lang.IllegalArgumentException: The first transformer or estimator object (Python class sklearn.feature_selection.univariate_selection.SelectKBest) does not specify feature type information
	at sklearn2pmml.pipeline.PMMLPipeline.encodePMML(PMMLPipeline.java:199)
	at org.jpmml.sklearn.Main.run(Main.java:145)
	at org.jpmml.sklearn.Main.main(Main.java:94)
Caused by: java.lang.UnsupportedOperationException
	at sklearn.MultiTransformer.getOpType(MultiTransformer.java:33)
	at sklearn2pmml.pipeline.PMMLPipeline.encodePMML(PMMLPipeline.java:189)
	... 2 more

-bash-4.2$
```

**Comment by vruusmann** [comment]
The exception message is clear enough - the first step of a PMML pipeline cannot be a selector (ie. `SelectorMixin` subclass), because it doesn't contain/provide the required type information.
