### ISSUE TITLE
What is the best way to handle Boolean with missing value

### ISSUE THREAD

**Issue by TGalaxy** [jpmml/jpmml-sklearn#88]
I am training a neural network with one feature type Boolean with missing value. It is like [Nan, Nan, True, Nan, Nan,...] What is the best way of handling it? So far I've tried
(1) claim it categorical and fill in the missing data. The training worked. But when converting to pmml, jpmml-slearn complain:
```
java.lang.UnsupportedOperationException 
  at org.jpmml.converter.CategoricalFeature.toContinuousFeature(CategoricalFeature.java:67)
  at org.jpmml.converter.neural_network.NeuralNetworkUtil.createNeuralInputs(NeuralNetworkUtil.java:75)
  at sklearn.neural_network.MultilayerPerceptronUtil.encodeNeuralNetwork(MultilayerPerceptronUtil.java:71)
  at sklearn.neural_network.MLPClassifier.encodeModel(MLPClassifier.java:52) 
  at sklearn.neural_network.MLPClassifier.encodeModel(MLPClassifier.java:32) 
  at sklearn2pmml.pipeline.PMMLPipeline.encodePMML(PMMLPipeline.java:219)
  at org.jpmml.sklearn.Main.run(Main.java:145) 
  at org.jpmml.sklearn.Main.main(Main.java:94)
```

(2) I convert it to float (True -> 1.0) and then fill in missing and it worked. However it is less ideal in production since I need to add a step to convert to float

**Comment by TGalaxy** [comment]
Thanks @vruusmann for fixing the issue. Unfortunately it still throws out errors. I tried a few options:
(1) fill in missing as 0 
attrib,[CategoricalDomain(missing_value_treatment = "as_value", missing_value_replacement = 0)]
It was able to train successfully however it failed to convert to pmml

SEVERE: Failed to convert
java.lang.IllegalArgumentException: Field xxx has data type boolean
	at org.jpmml.converter.PMMLEncoder.toContinuous(PMMLEncoder.java:200)
	at org.jpmml.converter.CategoricalFeature.toContinuousFeature(CategoricalFeature.java:57)
	at org.jpmml.converter.neural_network.NeuralNetworkUtil.createNeuralInputs(NeuralNetworkUtil.java:75)
	at sklearn.neural_network.MultilayerPerceptronUtil.encodeNeuralNetwork(MultilayerPerceptronUtil.java:71)
	at sklearn.neural_network.MLPClassifier.encodeModel(MLPClassifier.java:52)
	at sklearn.neural_network.MLPClassifier.encodeModel(MLPClassifier.java:32)
	at sklearn2pmml.pipeline.PMMLPipeline.encodePMML(PMMLPipeline.java:215)
	at org.jpmml.sklearn.Main.run(Main.java:145)
	at org.jpmml.sklearn.Main.main(Main.java:94)

Exception in thread "main" java.lang.IllegalArgumentException: Field xxx has data type boolean
	at org.jpmml.converter.PMMLEncoder.toContinuous(PMMLEncoder.java:200)
	at org.jpmml.converter.CategoricalFeature.toContinuousFeature(CategoricalFeature.java:57)
	at org.jpmml.converter.neural_network.NeuralNetworkUtil.createNeuralInputs(NeuralNetworkUtil.java:75)
	at sklearn.neural_network.MultilayerPerceptronUtil.encodeNeuralNetwork(MultilayerPerceptronUtil.java:71)
	at sklearn.neural_network.MLPClassifier.encodeModel(MLPClassifier.java:52)
	at sklearn.neural_network.MLPClassifier.encodeModel(MLPClassifier.java:32)
	at sklearn2pmml.pipeline.PMMLPipeline.encodePMML(PMMLPipeline.java:215)
	at org.jpmml.sklearn.Main.run(Main.java:145)
	at org.jpmml.sklearn.Main.main(Main.java:94)

(2) fill in missing as False
attrib,[CategoricalDomain(missing_value_treatment = "as_value", missing_value_replacement = False)]
It was able to train successfully however it failed to convert to pmml

threw the same error

(3) filling in missing as 'False'
attrib,[CategoricalDomain(missing_value_treatment = "as_value", missing_value_replacement = 'False')]
failed to train. 
ValueError: could not convert string to float: 'False'

Is there anything not correct?

**Comment by vruusmann** [comment]
@TGalaxy  Are you using the latest SkLearn2PMML package version?

In principle, the following stack trace shouldn't happen (direct invocation of `CategoricalFeature#toContinuousFeature()`), because class `BooleanFeature` overrides this method now:
```
java.lang.IllegalArgumentException: Field xxx has data type boolean
	at org.jpmml.converter.PMMLEncoder.toContinuous(PMMLEncoder.java:200)
	at org.jpmml.converter.CategoricalFeature.toContinuousFeature(CategoricalFeature.java:57)
```

Override:
https://github.com/jpmml/jpmml-converter/blob/master/src/main/java/org/jpmml/converter/BooleanFeature.java#L48-L51

**Comment by TGalaxy** [comment]
Thanks @vruusmann for replying. That is indeed very strange. I looked further into 
`SEVERE: Failed to convert
java.lang.IllegalArgumentException: Field xxx has data type boolean
	at org.jpmml.converter.PMMLEncoder.toContinuous(PMMLEncoder.java:200)
	at org.jpmml.converter.CategoricalFeature.toContinuousFeature(CategoricalFeature.java:57)
	at org.jpmml.converter.neural_network.NeuralNetworkUtil.createNeuralInputs(NeuralNetworkUtil.java:75)`
It said error happened at line 75. 

However line 75 of https://github.com/jpmml/jpmml-converter/blob/master/src/main/java/org/jpmml/converter/neural_network/NeuralNetworkUtil.java#L75 is the process for features other than booleans. So perhaps we should take a look at BooleanFeature check at line 68? 
`	if(feature instanceof BooleanFeature){`

**Comment by vruusmann** [comment]
The problem is that the feature descriptor is `org.jpmml.converter.CategoricalFeature` at that point, but it should be `o.j.c.BooleanFeature`.

When I marked this issue as fixed, then I basically added a handler, which should lead all boolean-like categorical columns to become represented as `BooleanFeature`:
```java
// XXX: Should take place inside WildcardFeature#toCategoricalFeature(List<String>)
if((DataType.BOOLEAN).equals(categoricalFeature.getDataType()) && (Arrays.asList("false", "true")).equals(categoricalFeature.getValues())){
	categoricalFeature = new BooleanFeature(categoricalFeature.getEncoder(), categoricalFeature.getField());
}
```

Now, the problem is that this handler doesn't recognize your "xxx" column as boolean-like.

What's the data type of that column? it should be Python's `bool`.

**Comment by TGalaxy** [comment]
It is `category` . The reason why I didn't set to bool is as follows:
`pd.DataFrame([True,np.nan,True,np.nan])
True
NaN
True
NaN

pd.DataFrame([True,np.nan,True,np.nan]).loc[:,0].dtype
dtype('O')

pd.DataFrame([True,np.nan,True,np.nan]).astype('bool')
True
True
True
True


pd.DataFrame([True,np.nan,True,np.nan]).astype('category')
True
NaN
True
NaN
`

So astype('bool') converts all missing to True...
