### ISSUE TITLE
Error when saving pipeline to pmml file

### ISSUE THREAD

**Issue by chaupmcs** [jpmml/jpmml-sklearn#94]
Hi,
I'm trying to save a pipeline to a `pmml` file, but it gives me an error. 

    params = {'classifier__categorical_feature':[1, 2, 3, 4, 6, 7] }
    mapper = DataFrameMapper(
        [([column], CategoricalDomain()) for column in cate_cols] +
        [(['Hours', 'Income', 'Age'], ContinuousDomain(with_data = False))])

    classifier = lgb.LGBMClassifier(n_estimators=5, learning_rate=0.1, \
         num_leaves=10, max_depth=2)
    pipeline = PMMLPipeline([("mapper", mapper), ("classifier", classifier)])
    pipeline.fit(X = X_train, y = y_train, **params)

    sklearn2pmml(pipeline, base_link + "/pipeline_2.pmml")    # Error here

I hope you can help me out the issue. Thank you!

---- The error as below [(full the example's code and result here)](https://github.com/chaupmcs/example_saving_lgb_to_text/blob/master/example.ipynb)
Standard output is empty
Standard error:
Jan 31, 2019 10:08:15 PM org.jpmml.sklearn.Main run
INFO: Parsing PKL..
Jan 31, 2019 10:08:15 PM org.jpmml.sklearn.Main run
INFO: Parsed PKL in 43 ms.
Jan 31, 2019 10:08:15 PM org.jpmml.sklearn.Main run
INFO: Converting..
Jan 31, 2019 10:08:15 PM org.jpmml.sklearn.Main run
SEVERE: Failed to convert
java.lang.IndexOutOfBoundsException: Index: 13, Size: 13
	at java.util.ArrayList.rangeCheck(ArrayList.java:653)
	at java.util.ArrayList.get(ArrayList.java:429)
	at org.jpmml.lightgbm.Tree.selectValues(Tree.java:240)
	at org.jpmml.lightgbm.Tree.encodeNode(Tree.java:151)
	at org.jpmml.lightgbm.Tree.encodeNode(Tree.java:186)
	at org.jpmml.lightgbm.Tree.encodeTreeModel(Tree.java:94)
	at org.jpmml.lightgbm.ObjectiveFunction.createMiningModel(ObjectiveFunction.java:66)
	at org.jpmml.lightgbm.BinomialLogisticRegression.encodeMiningModel(BinomialLogisticRegression.java:49)
	at org.jpmml.lightgbm.GBDT.encodeMiningModel(GBDT.java:287)
	at lightgbm.sklearn.BoosterUtil.encodeModel(BoosterUtil.java:58)
	at lightgbm.sklearn.LGBMClassifier.encodeModel(LGBMClassifier.java:39)
	at lightgbm.sklearn.LGBMClassifier.encodeModel(LGBMClassifier.java:26)
	at sklearn2pmml.pipeline.PMMLPipeline.encodePMML(PMMLPipeline.java:215)
	at org.jpmml.sklearn.Main.run(Main.java:145)
	at org.jpmml.sklearn.Main.main(Main.java:94)

Exception in thread "main" java.lang.IndexOutOfBoundsException: Index: 13, Size: 13
	at java.util.ArrayList.rangeCheck(ArrayList.java:653)
	at java.util.ArrayList.get(ArrayList.java:429)
	at org.jpmml.lightgbm.Tree.selectValues(Tree.java:240)
	at org.jpmml.lightgbm.Tree.encodeNode(Tree.java:151)
	at org.jpmml.lightgbm.Tree.encodeNode(Tree.java:186)
	at org.jpmml.lightgbm.Tree.encodeTreeModel(Tree.java:94)
	at org.jpmml.lightgbm.ObjectiveFunction.createMiningModel(ObjectiveFunction.java:66)
	at org.jpmml.lightgbm.BinomialLogisticRegression.encodeMiningModel(BinomialLogisticRegression.java:49)
	at org.jpmml.lightgbm.GBDT.encodeMiningModel(GBDT.java:287)
	at lightgbm.sklearn.BoosterUtil.encodeModel(BoosterUtil.java:58)
	at lightgbm.sklearn.LGBMClassifier.encodeModel(LGBMClassifier.java:39)
	at lightgbm.sklearn.LGBMClassifier.encodeModel(LGBMClassifier.java:26)
	at sklearn2pmml.pipeline.PMMLPipeline.encodePMML(PMMLPipeline.java:215)
	at org.jpmml.sklearn.Main.run(Main.java:145)
	at org.jpmml.sklearn.Main.main(Main.java:94)

---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-15-8423ad078c43> in <module>()
----> 1 sklearn2pmml(pipeline, base_link + "/pipeline_2.pmml")

~/.local/lib/python3.6/site-packages/sklearn2pmml/__init__.py in sklearn2pmml(pipeline, pmml, user_classpath, with_repr, debug, java_encoding)
    244                                 print("Standard error is empty")
    245                 if retcode:
--> 246                         raise RuntimeError("The JPMML-SkLearn conversion application has failed. The Java executable should have printed more information about the failure into its standard output and/or standard error streams")
    247         finally:
    248                 if debug:

RuntimeError: The JPMML-SkLearn conversion application has failed. The Java executable should have printed more information about the failure into its standard output and/or standard error streams

**Comment by chaupmcs** [comment]
@vruusmann Thanks for the very quick reply.

I re-ordered the columns, put categorial features go first, but the issue's still there.

Please take a look at the [example](https://github.com/chaupmcs/example_saving_lgb_to_text/blob/master/example.ipynb). I've just updated the code there. Thanks!

**Comment by vruusmann** [comment]
In my JPMML-SkLearn integration test (shared with you in the original LightGBM thread, go look it up) I use the following column transformation pipeline: `[CategoricalDomain(), LabelEncoder()]`. You only do: `CategoricalDomain()`.

Please take my integration test code, and execute it as-is. Works in my computer.

**Comment by chaupmcs** [comment]
@vruusmann  You're right. I didn't put `LabelEncoder()` in my example. 

Thanks a lot! I will read your examples more careful.
